package khanzahmsanjungan;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Kode
 */
public class DlgCariJadwalDokterBPJS extends javax.swing.JDialog {
    
    private final DefaultTableModel tabMode;
    private final Connection koneksi = koneksiDB.condb();
    private final validasi Valid = new validasi();
    private TableColumn column;

    public DlgCariJadwalDokterBPJS(java.awt.Frame parent, boolean id) {
        super(parent, id);
        initComponents();
        
        String[] row = {"kodePoliBPJS", "kodeDokterBPJS", "hari", "kodePoli",
                        "kodeDokter", "Nama Dokter", "Jam Mulai",
                        "Jam Selesai", "Kuota"};
        tabMode = new DefaultTableModel(null, row) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class getColumnClass(int columnIndex) {
                if (columnIndex == 9) {
                    return java.lang.Integer.class;
                }
                return java.lang.String.class;
            }
        };
        
        tbJadwalPoli.setModel(tabMode);
        for (int i = 0; i < row.length; i++) {
            column = tbJadwalPoli.getColumnModel().getColumn(i);
            if (i <= 4) {
                column.setMinWidth(0);
                column.setMaxWidth(0);
            } else if (i == 5) {
                column.setPreferredWidth(200);
            } else if (i == 6) {
                column.setPreferredWidth(130);
            } else if (i == 7) {
                column.setPreferredWidth(90);
            } else if (i == 8) {
                column.setPreferredWidth(90);
            } else if (i == 9) {
                column.setPreferredWidth(75);
            }
        }
        column = null;
        tbJadwalPoli.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new component.Panel();
        scrollPane1 = new widget.ScrollPane();
        tbJadwalPoli = new widget.Table();
        jPanel3 = new javax.swing.JPanel();
        labelPoli = new widget.Label();
        namaPoli = new widget.TextBox();
        labelPoli1 = new widget.Label();
        batal = new component.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(1, 1));

        jPanel1.setBackground(new java.awt.Color(238, 238, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 255)), "CARI JADWAL DOKTER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 24), new java.awt.Color(0, 131, 62))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(543, 106));
        jPanel1.setPreferredSize(new java.awt.Dimension(543, 106));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 1));

        tbJadwalPoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane1.setViewportView(tbJadwalPoli);

        jPanel1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(238, 238, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(533, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(533, 60));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelPoli.setForeground(new java.awt.Color(0, 131, 62));
        labelPoli.setText("Poliklinik :");
        labelPoli.setFont(new java.awt.Font("Inter Display SemiBold", 0, 14)); // NOI18N
        labelPoli.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel3.add(labelPoli);

        namaPoli.setEditable(false);
        namaPoli.setBackground(new java.awt.Color(245, 250, 240));
        namaPoli.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 192, 223)), javax.swing.BorderFactory.createEmptyBorder(2, 4, 2, 4)));
        namaPoli.setHighlighter(null);
        namaPoli.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel3.add(namaPoli);

        labelPoli1.setForeground(new java.awt.Color(0, 131, 62));
        labelPoli1.setFont(new java.awt.Font("Inter Display SemiBold", 0, 14)); // NOI18N
        labelPoli1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel3.add(labelPoli1);

        batal.setForeground(new java.awt.Color(0, 131, 62));
        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/exit.png"))); // NOI18N
        batal.setMnemonic('K');
        batal.setToolTipText("Alt+K");
        batal.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        batal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        batal.setPreferredSize(new java.awt.Dimension(30, 30));
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel3.add(batal);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        dispose();
    }//GEN-LAST:event_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCariJadwalDokterBPJS dialog = new DlgCariJadwalDokterBPJS(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Button batal;
    private component.Panel jPanel1;
    private javax.swing.JPanel jPanel3;
    private widget.Label labelPoli;
    private widget.Label labelPoli1;
    private widget.TextBox namaPoli;
    private widget.ScrollPane scrollPane1;
    private widget.Table tbJadwalPoli;
    // End of variables declaration//GEN-END:variables

    public void tampil(String hari, String kodePoliRS, String namaPoliBPJS) {
        Valid.tabelKosong(tabMode);
        namaPoli.setText(namaPoliBPJS);
        
        try (PreparedStatement ps = koneksi.prepareStatement(
            "select maping_poli_bpjs.kd_poli_bpjs, maping_dokter_dpjpvclaim.kd_dokter_bpjs, jadwal.kd_poli, jadwal.kd_dokter, " +
            "jadwal.hari_kerja, maping_dokter_dpjpvclaim.nm_dokter_bpjs, jadwal.jam_mulai, jadwal.jam_selesai, jadwal.kuota " +
            "from jadwal join maping_dokter_dpjpvclaim on jadwal.kd_dokter = maping_dokter_dpjpvclaim.kd_dokter join " +
            "maping_poli_bpjs on jadwal.kd_poli = maping_poli_bpjs.kd_poli_rs where jadwal.hari_kerja = ? and jadwal.kd_poli = ? " +
            "order by jadwal.jam_mulai"
        )) {
            ps.setString(1, hari);
            ps.setString(2, kodePoliRS);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    tabMode.addRow(new Object[] {
                        rs.getString("kd_poli_bpjs"), rs.getString("kd_dokter_bpjs"), rs.getString("kd_poli"),
                        rs.getString("kd_dokter"), rs.getString("hari_kerja"), rs.getString("nm_dokter_bpjs"),
                        rs.getString("jam_mulai").substring(0, 5) + "-" + rs.getString("jam_selesai").substring(0, 5),
                        rs.getString("kuota")
                    });
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }
    
    public JTable getTable() {
        return tbJadwalPoli;
    }
}
